name: Generate docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-and-publish-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install linkml

    - name: Generate Markdown Documentation
      run: |
        gen-markdown -d docs linkml/seagrass.yaml

    - name: Add Jekyll Config
      run: |
        cat <<EOL > docs/_config.yml
        markdown: kramdown
        theme: minima
        EOL

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs
        publish_branch: gh-pages
